baseURL = "http://zonglin-li6565.github.io/"
languageCode = "en-us"
title = "My Programming Notes"
disqusShortname = "my-programming-note"
theme = "hemingway"
copyright = "&copy; <a href=\"https://github.com/Zonglin-Li6565\">Zonglin Li</a> 2017"

[taxonomies]
tag = "tags"
category = "categories"

[params]

[params.highlight]
style = "github"
languages = ["python", "C++", "Java"]

[[params.social]]
url = "https://github.com/Zonglin-Li6565"
fa_icon = "fa-github"

